### Base URL
http://microbloglite.us-east-2.elasticbeanstalk.com

### Step 1) Register or create new user
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Content-Type: application/json

{
  "username": "scotty",
  "fullName": "scott dot",
  "password": "bugsbunny"
}


### Step 2) Login
POST http://microbloglite.us-east-2.elasticbeanstalk.com/auth/login
Content-Type: application/json

{
  "username": "scotty",
  "password": "bulbasaur"
}


### Step 3) GET Users
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4Y

### Step 4) GET One User
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/sora
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4


### Step 5) Create a Post
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

{
  "text": "I can swallow a bottle of alcohol and I'll feel like Godzilla"
}

### Step 6) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts?limit=100&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

### Step 6b) Get a Post
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a144fbf13c2cc0eaf6ff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

### Step 7) DELETE Post
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a53ffbf13c2cc0eaf7ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

### Step 8) Update User
PUT http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/scotty
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

{
  "username": "scotty",
  "password": "bulbasaur",
  "bio": "will the real slim shady please stand up",
  "fullName": "scott dot"
}

### Step 9) Add Like
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4

{
  "postId": "6675a089fbf13c2cc0eaf6df"
}

### Step 10) Delete/Remove Like
DELETE  http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes/6675a538fbf13c2cc0eaf7e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjb3R0eSIsImlhdCI6MTcxOTM3NTkxNywiZXhwIjoxNzE5NDYyMzE3fQ.fEXpPet6YmjIXBcHDd0izWGIvnpwyuskhrG9pKlzHM4